# Character Classification Using Perceptron (Multiclass: A, B, C)

In [1]:
import numpy as np

In [2]:
A_train = [
    [0,1,0, 1,0,1, 1,1,1],
    [0,1,0, 1,1,1, 1,0,1],
    [0,1,0, 1,0,1, 1,1,0],
    [0,1,0, 1,1,0, 1,1,1],
    [0,1,0, 0,1,1, 1,1,1],
    [1,1,0, 1,0,1, 1,1,1],
]

B_train = [
    [1,1,0, 1,0,1, 1,1,0],
    [1,1,1, 1,0,1, 1,1,0],
    [1,1,0, 1,0,1, 1,1,1],
    [1,1,1, 1,1,0, 1,1,0],
    [1,1,0, 1,1,1, 1,1,0],
    [1,1,1, 1,0,1, 1,0,1],
]

In [3]:
C_train = [
    [0,1,1, 1,0,0, 0,1,1],
    [1,1,1, 1,0,0, 1,1,1],
    [0,1,0, 1,0,0, 0,1,1],
    [0,1,1, 1,1,0, 0,1,1],
    [1,1,1, 1,0,0, 0,1,0],
    [1,1,1, 1,0,0, 1,1,0],
]

In [4]:
X_train = np.array(A_train + B_train + C_train)
print('Train Data:\n', X_train)

y_train = np.array([[1,0,0]]*len(A_train) + [[0,1,0]]*len(B_train) + [[0,0,1]]*len(C_train))
print('\nLabels:\n', y_train)

Train Data:
 [[0 1 0 1 0 1 1 1 1]
 [0 1 0 1 1 1 1 0 1]
 [0 1 0 1 0 1 1 1 0]
 [0 1 0 1 1 0 1 1 1]
 [0 1 0 0 1 1 1 1 1]
 [1 1 0 1 0 1 1 1 1]
 [1 1 0 1 0 1 1 1 0]
 [1 1 1 1 0 1 1 1 0]
 [1 1 0 1 0 1 1 1 1]
 [1 1 1 1 1 0 1 1 0]
 [1 1 0 1 1 1 1 1 0]
 [1 1 1 1 0 1 1 0 1]
 [0 1 1 1 0 0 0 1 1]
 [1 1 1 1 0 0 1 1 1]
 [0 1 0 1 0 0 0 1 1]
 [0 1 1 1 1 0 0 1 1]
 [1 1 1 1 0 0 0 1 0]
 [1 1 1 1 0 0 1 1 0]]

Labels:
 [[1 0 0]
 [1 0 0]
 [1 0 0]
 [1 0 0]
 [1 0 0]
 [1 0 0]
 [0 1 0]
 [0 1 0]
 [0 1 0]
 [0 1 0]
 [0 1 0]
 [0 1 0]
 [0 0 1]
 [0 0 1]
 [0 0 1]
 [0 0 1]
 [0 0 1]
 [0 0 1]]


In [5]:
A_test = [0,1,0, 1,0,1, 1,0,1]
B_test = [1,1,0, 1,1,1, 1,1,0]
C_test = [0,1,1, 1,0,0, 0,1,1]

X_test = np.array([A_test, B_test, C_test])
print('Test Data:\n', X_test)

y_test = np.array([[1,0,0], [0,1,0], [0,0,1]])
print('\nTest Labels:\n', y_test)

Test Data:
 [[0 1 0 1 0 1 1 0 1]
 [1 1 0 1 1 1 1 1 0]
 [0 1 1 1 0 0 0 1 1]]

Test Labels:
 [[1 0 0]
 [0 1 0]
 [0 0 1]]


In [6]:
def sigmoid(x):
    return 1 / (1 + np.exp(-x))

In [7]:
def sigmoid_derivative(x):
    return x * (1 - x)

In [8]:
def softmax(x):
    e_x = np.exp(x - np.max(x))
    return e_x / np.sum(e_x, axis=1, keepdims=True)

In [9]:
def cross_entropy(predictions, labels):
    epsilon = 1e-12
    predictions = np.clip(predictions, epsilon, 1. - epsilon)
    return -np.mean(np.sum(labels * np.log(predictions), axis=1))

In [10]:
input_size = 9
hidden_size = 6
output_size = 3
lr = 0.1
epochs = 1000

W1 = np.random.randn(input_size, hidden_size)
b1 = np.zeros((1, hidden_size))
W2 = np.random.randn(hidden_size, output_size)
b2 = np.zeros((1, output_size))

In [11]:
for epoch in range(epochs):
    # Forward pass
    z1 = np.dot(X_train, W1) + b1
    a1 = sigmoid(z1)
    z2 = np.dot(a1, W2) + b2
    y_pred = softmax(z2)

    loss = cross_entropy(y_pred, y_train)

    # Backpropagation
    dL_dz2 = y_pred - y_train
    dL_dW2 = np.dot(a1.T, dL_dz2)
    dL_db2 = np.sum(dL_dz2, axis=0, keepdims=True)

    dL_da1 = np.dot(dL_dz2, W2.T)
    dL_dz1 = dL_da1 * sigmoid_derivative(a1)
    dL_dW1 = np.dot(X_train.T, dL_dz1)
    dL_db1 = np.sum(dL_dz1, axis=0, keepdims=True)

    # Update Weights
    W2 -= lr * dL_dW2
    b2 -= lr * dL_db2
    W1 -= lr * dL_dW1
    b1 -= lr * dL_db1

    if (epoch+1) % 50 == 0 or epoch == 0:
        print(f"Epoch {epoch+1} | Loss: {loss:.4f}")

Epoch 1 | Loss: 1.8718
Epoch 50 | Loss: 0.1917
Epoch 100 | Loss: 0.1171
Epoch 150 | Loss: 0.1000
Epoch 200 | Loss: 0.0929
Epoch 250 | Loss: 0.0890
Epoch 300 | Loss: 0.0916
Epoch 350 | Loss: 0.0874
Epoch 400 | Loss: 0.0859
Epoch 450 | Loss: 0.0847
Epoch 500 | Loss: 0.0838
Epoch 550 | Loss: 0.0831
Epoch 600 | Loss: 0.0825
Epoch 650 | Loss: 0.0820
Epoch 700 | Loss: 0.0816
Epoch 750 | Loss: 0.0812
Epoch 800 | Loss: 0.0809
Epoch 850 | Loss: 0.0807
Epoch 900 | Loss: 0.0804
Epoch 950 | Loss: 0.0802
Epoch 1000 | Loss: 0.0800


In [12]:
# Prediction on Test Data
z1_test = np.dot(X_test, W1) + b1
a1_test = sigmoid(z1_test)
z2_test = np.dot(a1_test, W2) + b2
y_pred_test = softmax(z2_test)

predicted_classes = np.argmax(y_pred_test, axis=1)
true_classes = np.argmax(y_test, axis=1)

print("\nTest results")
for i in range(len(X_test)):
    print(f"Predicted Label: {predicted_classes[i]}, True Label: {true_classes[i]} - {'✅ True' if predicted_classes[i]==true_classes[i] else '❌ False'}")

accuracy = np.mean(predicted_classes == true_classes)
print(f"\nAccuracy: {accuracy * 100:.2f}%")


Test results
Predicted Label: 0, True Label: 0 - ✅ True
Predicted Label: 1, True Label: 1 - ✅ True
Predicted Label: 2, True Label: 2 - ✅ True

Accuracy: 100.00%
